namespace Veterinary
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.animalbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ownerbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.appointmentbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.consultationbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.paymentbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.storebtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.pictureBox3 = new System.Windows.Forms.PictureBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.doctorname = new System.Windows.Forms.Label();
            this.close = new System.Windows.Forms.PictureBox();
            this.pensbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.treatmentbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.flowLayoutPanel1 = new System.Windows.Forms.FlowLayoutPanel();
            this.label3 = new System.Windows.Forms.Label();
            this.pictureBox4 = new System.Windows.Forms.PictureBox();
            this.ordersbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.medbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.close)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox4)).BeginInit();
            this.SuspendLayout();
            // 
            // animalbtn
            // 
            this.animalbtn.AllowAnimations = true;
            this.animalbtn.AllowMouseEffects = true;
            this.animalbtn.AllowToggling = false;
            this.animalbtn.AnimationSpeed = 200;
            this.animalbtn.AutoGenerateColors = false;
            this.animalbtn.AutoRoundBorders = false;
            this.animalbtn.AutoSizeLeftIcon = true;
            this.animalbtn.AutoSizeRightIcon = true;
            this.animalbtn.BackColor = System.Drawing.Color.Transparent;
            this.animalbtn.BackColor1 = System.Drawing.Color.Transparent;
            this.animalbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("animalbtn.BackgroundImage")));
            this.animalbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.animalbtn.ButtonText = "  Animal";
            this.animalbtn.ButtonTextMarginLeft = 0;
            this.animalbtn.ColorContrastOnClick = 45;
            this.animalbtn.ColorContrastOnHover = 45;
            this.animalbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.animalbtn.CustomizableEdges = borderEdges1;
            this.animalbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.animalbtn.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.animalbtn.DisabledFillColor = System.Drawing.Color.Transparent;
            this.animalbtn.DisabledForecolor = System.Drawing.Color.White;
            this.animalbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.animalbtn.Font = new System.Drawing.Font("Calibri", 10.875F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.animalbtn.ForeColor = System.Drawing.Color.White;
            this.animalbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.animalbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.animalbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.animalbtn.IconMarginLeft = 11;
            this.animalbtn.IconPadding = 10;
            this.animalbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.animalbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.animalbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.animalbtn.IconSize = 20;
            this.animalbtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.animalbtn.IdleBorderRadius = 30;
            this.animalbtn.IdleBorderThickness = 1;
            this.animalbtn.IdleFillColor = System.Drawing.Color.Transparent;
            this.animalbtn.IdleIconLeftImage = global::Veterinary.Properties.Resources.icons8_pet_96;
            this.animalbtn.IdleIconRightImage = null;
            this.animalbtn.IndicateFocus = false;
            this.animalbtn.Location = new System.Drawing.Point(348, 19);
            this.animalbtn.Margin = new System.Windows.Forms.Padding(2);
            this.animalbtn.Name = "animalbtn";
            this.animalbtn.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.animalbtn.OnDisabledState.BorderRadius = 30;
            this.animalbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.animalbtn.OnDisabledState.BorderThickness = 1;
            this.animalbtn.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.animalbtn.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.animalbtn.OnDisabledState.IconLeftImage = null;
            this.animalbtn.OnDisabledState.IconRightImage = null;
            this.animalbtn.onHoverState.BorderColor = System.Drawing.Color.Turquoise;
            this.animalbtn.onHoverState.BorderRadius = 30;
            this.animalbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.animalbtn.onHoverState.BorderThickness = 1;
            this.animalbtn.onHoverState.FillColor = System.Drawing.Color.Turquoise;
            this.animalbtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.animalbtn.onHoverState.IconLeftImage = null;
            this.animalbtn.onHoverState.IconRightImage = null;
            this.animalbtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.animalbtn.OnIdleState.BorderRadius = 30;
            this.animalbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.animalbtn.OnIdleState.BorderThickness = 1;
            this.animalbtn.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.animalbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.animalbtn.OnIdleState.IconLeftImage = global::Veterinary.Properties.Resources.icons8_pet_96;
            this.animalbtn.OnIdleState.IconRightImage = null;
            this.animalbtn.OnPressedState.BorderColor = System.Drawing.Color.LightSeaGreen;
            this.animalbtn.OnPressedState.BorderRadius = 30;
            this.animalbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.animalbtn.OnPressedState.BorderThickness = 1;
            this.animalbtn.OnPressedState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.animalbtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.animalbtn.OnPressedState.IconLeftImage = null;
            this.animalbtn.OnPressedState.IconRightImage = null;
            this.animalbtn.Size = new System.Drawing.Size(145, 45);
            this.animalbtn.TabIndex = 0;
            this.animalbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.animalbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.animalbtn.TextMarginLeft = 0;
            this.animalbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.animalbtn.UseDefaultRadiusAndThickness = true;
            this.animalbtn.Click += new System.EventHandler(this.animalbtn_Click);
            // 
            // ownerbtn
            // 
            this.ownerbtn.AllowAnimations = true;
            this.ownerbtn.AllowMouseEffects = true;
            this.ownerbtn.AllowToggling = false;
            this.ownerbtn.AnimationSpeed = 200;
            this.ownerbtn.AutoGenerateColors = false;
            this.ownerbtn.AutoRoundBorders = false;
            this.ownerbtn.AutoSizeLeftIcon = true;
            this.ownerbtn.AutoSizeRightIcon = true;
            this.ownerbtn.BackColor = System.Drawing.Color.Transparent;
            this.ownerbtn.BackColor1 = System.Drawing.Color.Transparent;
            this.ownerbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ownerbtn.BackgroundImage")));
            this.ownerbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ownerbtn.ButtonText = "  Owner";
            this.ownerbtn.ButtonTextMarginLeft = 0;
            this.ownerbtn.ColorContrastOnClick = 45;
            this.ownerbtn.ColorContrastOnHover = 45;
            this.ownerbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.ownerbtn.CustomizableEdges = borderEdges2;
            this.ownerbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ownerbtn.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.ownerbtn.DisabledFillColor = System.Drawing.Color.Transparent;
            this.ownerbtn.DisabledForecolor = System.Drawing.Color.White;
            this.ownerbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ownerbtn.Font = new System.Drawing.Font("Calibri", 10.875F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ownerbtn.ForeColor = System.Drawing.Color.White;
            this.ownerbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ownerbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ownerbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ownerbtn.IconMarginLeft = 11;
            this.ownerbtn.IconPadding = 10;
            this.ownerbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ownerbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ownerbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ownerbtn.IconSize = 20;
            this.ownerbtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.ownerbtn.IdleBorderRadius = 30;
            this.ownerbtn.IdleBorderThickness = 1;
            this.ownerbtn.IdleFillColor = System.Drawing.Color.Transparent;
            this.ownerbtn.IdleIconLeftImage = global::Veterinary.Properties.Resources.icons8_client_90;
            this.ownerbtn.IdleIconRightImage = null;
            this.ownerbtn.IndicateFocus = false;
            this.ownerbtn.Location = new System.Drawing.Point(497, 19);
            this.ownerbtn.Margin = new System.Windows.Forms.Padding(2);
            this.ownerbtn.Name = "ownerbtn";
            this.ownerbtn.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.ownerbtn.OnDisabledState.BorderRadius = 30;
            this.ownerbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ownerbtn.OnDisabledState.BorderThickness = 1;
            this.ownerbtn.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.ownerbtn.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.ownerbtn.OnDisabledState.IconLeftImage = null;
            this.ownerbtn.OnDisabledState.IconRightImage = null;
            this.ownerbtn.onHoverState.BorderColor = System.Drawing.Color.Turquoise;
            this.ownerbtn.onHoverState.BorderRadius = 30;
            this.ownerbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ownerbtn.onHoverState.BorderThickness = 1;
            this.ownerbtn.onHoverState.FillColor = System.Drawing.Color.Turquoise;
            this.ownerbtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ownerbtn.onHoverState.IconLeftImage = null;
            this.ownerbtn.onHoverState.IconRightImage = null;
            this.ownerbtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.ownerbtn.OnIdleState.BorderRadius = 30;
            this.ownerbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ownerbtn.OnIdleState.BorderThickness = 1;
            this.ownerbtn.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.ownerbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.ownerbtn.OnIdleState.IconLeftImage = global::Veterinary.Properties.Resources.icons8_client_90;
            this.ownerbtn.OnIdleState.IconRightImage = null;
            this.ownerbtn.OnPressedState.BorderColor = System.Drawing.Color.LightSeaGreen;
            this.ownerbtn.OnPressedState.BorderRadius = 30;
            this.ownerbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ownerbtn.OnPressedState.BorderThickness = 1;
            this.ownerbtn.OnPressedState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.ownerbtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ownerbtn.OnPressedState.IconLeftImage = null;
            this.ownerbtn.OnPressedState.IconRightImage = null;
            this.ownerbtn.Size = new System.Drawing.Size(145, 45);
            this.ownerbtn.TabIndex = 0;
            this.ownerbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ownerbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ownerbtn.TextMarginLeft = 0;
            this.ownerbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.ownerbtn.UseDefaultRadiusAndThickness = true;
            this.ownerbtn.Click += new System.EventHandler(this.ownerbtn_Click);
            // 
            // appointmentbtn
            // 
            this.appointmentbtn.AllowAnimations = true;
            this.appointmentbtn.AllowMouseEffects = true;
            this.appointmentbtn.AllowToggling = false;
            this.appointmentbtn.AnimationSpeed = 200;
            this.appointmentbtn.AutoGenerateColors = false;
            this.appointmentbtn.AutoRoundBorders = false;
            this.appointmentbtn.AutoSizeLeftIcon = true;
            this.appointmentbtn.AutoSizeRightIcon = true;
            this.appointmentbtn.BackColor = System.Drawing.Color.Transparent;
            this.appointmentbtn.BackColor1 = System.Drawing.Color.Transparent;
            this.appointmentbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("appointmentbtn.BackgroundImage")));
            this.appointmentbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.appointmentbtn.ButtonText = "Appointment";
            this.appointmentbtn.ButtonTextMarginLeft = 0;
            this.appointmentbtn.ColorContrastOnClick = 45;
            this.appointmentbtn.ColorContrastOnHover = 45;
            this.appointmentbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.appointmentbtn.CustomizableEdges = borderEdges3;
            this.appointmentbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.appointmentbtn.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.appointmentbtn.DisabledFillColor = System.Drawing.Color.Transparent;
            this.appointmentbtn.DisabledForecolor = System.Drawing.Color.White;
            this.appointmentbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.appointmentbtn.Font = new System.Drawing.Font("Calibri", 10.875F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.appointmentbtn.ForeColor = System.Drawing.Color.White;
            this.appointmentbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.appointmentbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.appointmentbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.appointmentbtn.IconMarginLeft = 11;
            this.appointmentbtn.IconPadding = 10;
            this.appointmentbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.appointmentbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.appointmentbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.appointmentbtn.IconSize = 20;
            this.appointmentbtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.appointmentbtn.IdleBorderRadius = 30;
            this.appointmentbtn.IdleBorderThickness = 1;
            this.appointmentbtn.IdleFillColor = System.Drawing.Color.Transparent;
            this.appointmentbtn.IdleIconLeftImage = global::Veterinary.Properties.Resources.icons8_appointment_68;
            this.appointmentbtn.IdleIconRightImage = null;
            this.appointmentbtn.IndicateFocus = false;
            this.appointmentbtn.Location = new System.Drawing.Point(646, 19);
            this.appointmentbtn.Margin = new System.Windows.Forms.Padding(2);
            this.appointmentbtn.Name = "appointmentbtn";
            this.appointmentbtn.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.appointmentbtn.OnDisabledState.BorderRadius = 30;
            this.appointmentbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.appointmentbtn.OnDisabledState.BorderThickness = 1;
            this.appointmentbtn.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.appointmentbtn.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.appointmentbtn.OnDisabledState.IconLeftImage = null;
            this.appointmentbtn.OnDisabledState.IconRightImage = null;
            this.appointmentbtn.onHoverState.BorderColor = System.Drawing.Color.Turquoise;
            this.appointmentbtn.onHoverState.BorderRadius = 30;
            this.appointmentbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.appointmentbtn.onHoverState.BorderThickness = 1;
            this.appointmentbtn.onHoverState.FillColor = System.Drawing.Color.Turquoise;
            this.appointmentbtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.appointmentbtn.onHoverState.IconLeftImage = null;
            this.appointmentbtn.onHoverState.IconRightImage = null;
            this.appointmentbtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.appointmentbtn.OnIdleState.BorderRadius = 30;
            this.appointmentbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.appointmentbtn.OnIdleState.BorderThickness = 1;
            this.appointmentbtn.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.appointmentbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.appointmentbtn.OnIdleState.IconLeftImage = global::Veterinary.Properties.Resources.icons8_appointment_68;
            this.appointmentbtn.OnIdleState.IconRightImage = null;
            this.appointmentbtn.OnPressedState.BorderColor = System.Drawing.Color.LightSeaGreen;
            this.appointmentbtn.OnPressedState.BorderRadius = 30;
            this.appointmentbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.appointmentbtn.OnPressedState.BorderThickness = 1;
            this.appointmentbtn.OnPressedState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.appointmentbtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.appointmentbtn.OnPressedState.IconLeftImage = null;
            this.appointmentbtn.OnPressedState.IconRightImage = null;
            this.appointmentbtn.Size = new System.Drawing.Size(219, 45);
            this.appointmentbtn.TabIndex = 0;
            this.appointmentbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.appointmentbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.appointmentbtn.TextMarginLeft = 0;
            this.appointmentbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.appointmentbtn.UseDefaultRadiusAndThickness = true;
            this.appointmentbtn.Click += new System.EventHandler(this.appointmentbtn_Click);
            // 
            // consultationbtn
            // 
            this.consultationbtn.AllowAnimations = true;
            this.consultationbtn.AllowMouseEffects = true;
            this.consultationbtn.AllowToggling = false;
            this.consultationbtn.AnimationSpeed = 200;
            this.consultationbtn.AutoGenerateColors = false;
            this.consultationbtn.AutoRoundBorders = false;
            this.consultationbtn.AutoSizeLeftIcon = true;
            this.consultationbtn.AutoSizeRightIcon = true;
            this.consultationbtn.BackColor = System.Drawing.Color.Transparent;
            this.consultationbtn.BackColor1 = System.Drawing.Color.Transparent;
            this.consultationbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("consultationbtn.BackgroundImage")));
            this.consultationbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.consultationbtn.ButtonText = "Consultation";
            this.consultationbtn.ButtonTextMarginLeft = 0;
            this.consultationbtn.ColorContrastOnClick = 45;
            this.consultationbtn.ColorContrastOnHover = 45;
            this.consultationbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.consultationbtn.CustomizableEdges = borderEdges4;
            this.consultationbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.consultationbtn.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.consultationbtn.DisabledFillColor = System.Drawing.Color.Transparent;
            this.consultationbtn.DisabledForecolor = System.Drawing.Color.White;
            this.consultationbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.consultationbtn.Font = new System.Drawing.Font("Calibri", 10.875F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.consultationbtn.ForeColor = System.Drawing.Color.White;
            this.consultationbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.consultationbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.consultationbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.consultationbtn.IconMarginLeft = 11;
            this.consultationbtn.IconPadding = 10;
            this.consultationbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.consultationbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.consultationbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.consultationbtn.IconSize = 20;
            this.consultationbtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.consultationbtn.IdleBorderRadius = 30;
            this.consultationbtn.IdleBorderThickness = 1;
            this.consultationbtn.IdleFillColor = System.Drawing.Color.Transparent;
            this.consultationbtn.IdleIconLeftImage = global::Veterinary.Properties.Resources.icons8_vet_consultation_64;
            this.consultationbtn.IdleIconRightImage = null;
            this.consultationbtn.IndicateFocus = false;
            this.consultationbtn.Location = new System.Drawing.Point(869, 19);
            this.consultationbtn.Margin = new System.Windows.Forms.Padding(2);
            this.consultationbtn.Name = "consultationbtn";
            this.consultationbtn.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.consultationbtn.OnDisabledState.BorderRadius = 30;
            this.consultationbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.consultationbtn.OnDisabledState.BorderThickness = 1;
            this.consultationbtn.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.consultationbtn.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.consultationbtn.OnDisabledState.IconLeftImage = null;
            this.consultationbtn.OnDisabledState.IconRightImage = null;
            this.consultationbtn.onHoverState.BorderColor = System.Drawing.Color.Turquoise;
            this.consultationbtn.onHoverState.BorderRadius = 30;
            this.consultationbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.consultationbtn.onHoverState.BorderThickness = 1;
            this.consultationbtn.onHoverState.FillColor = System.Drawing.Color.Turquoise;
            this.consultationbtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.consultationbtn.onHoverState.IconLeftImage = null;
            this.consultationbtn.onHoverState.IconRightImage = null;
            this.consultationbtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.consultationbtn.OnIdleState.BorderRadius = 30;
            this.consultationbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.consultationbtn.OnIdleState.BorderThickness = 1;
            this.consultationbtn.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.consultationbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.consultationbtn.OnIdleState.IconLeftImage = global::Veterinary.Properties.Resources.icons8_vet_consultation_64;
            this.consultationbtn.OnIdleState.IconRightImage = null;
            this.consultationbtn.OnPressedState.BorderColor = System.Drawing.Color.LightSeaGreen;
            this.consultationbtn.OnPressedState.BorderRadius = 30;
            this.consultationbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.consultationbtn.OnPressedState.BorderThickness = 1;
            this.consultationbtn.OnPressedState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.consultationbtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.consultationbtn.OnPressedState.IconLeftImage = null;
            this.consultationbtn.OnPressedState.IconRightImage = null;
            this.consultationbtn.Size = new System.Drawing.Size(219, 45);
            this.consultationbtn.TabIndex = 0;
            this.consultationbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.consultationbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.consultationbtn.TextMarginLeft = 0;
            this.consultationbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.consultationbtn.UseDefaultRadiusAndThickness = true;
            this.consultationbtn.Click += new System.EventHandler(this.consultationbtn_Click);
            // 
            // paymentbtn
            // 
            this.paymentbtn.AllowAnimations = true;
            this.paymentbtn.AllowMouseEffects = true;
            this.paymentbtn.AllowToggling = false;
            this.paymentbtn.AnimationSpeed = 200;
            this.paymentbtn.AutoGenerateColors = false;
            this.paymentbtn.AutoRoundBorders = false;
            this.paymentbtn.AutoSizeLeftIcon = true;
            this.paymentbtn.AutoSizeRightIcon = true;
            this.paymentbtn.BackColor = System.Drawing.Color.Transparent;
            this.paymentbtn.BackColor1 = System.Drawing.Color.Transparent;
            this.paymentbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("paymentbtn.BackgroundImage")));
            this.paymentbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.paymentbtn.ButtonText = "Payment";
            this.paymentbtn.ButtonTextMarginLeft = 0;
            this.paymentbtn.ColorContrastOnClick = 45;
            this.paymentbtn.ColorContrastOnHover = 45;
            this.paymentbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.paymentbtn.CustomizableEdges = borderEdges5;
            this.paymentbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.paymentbtn.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.paymentbtn.DisabledFillColor = System.Drawing.Color.Transparent;
            this.paymentbtn.DisabledForecolor = System.Drawing.Color.White;
            this.paymentbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.paymentbtn.Font = new System.Drawing.Font("Calibri", 10.875F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.paymentbtn.ForeColor = System.Drawing.Color.White;
            this.paymentbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.paymentbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.paymentbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.paymentbtn.IconMarginLeft = 11;
            this.paymentbtn.IconPadding = 10;
            this.paymentbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.paymentbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.paymentbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.paymentbtn.IconSize = 25;
            this.paymentbtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.paymentbtn.IdleBorderRadius = 30;
            this.paymentbtn.IdleBorderThickness = 1;
            this.paymentbtn.IdleFillColor = System.Drawing.Color.Transparent;
            this.paymentbtn.IdleIconLeftImage = global::Veterinary.Properties.Resources.icons8_money_96;
            this.paymentbtn.IdleIconRightImage = null;
            this.paymentbtn.IndicateFocus = false;
            this.paymentbtn.Location = new System.Drawing.Point(691, 77);
            this.paymentbtn.Margin = new System.Windows.Forms.Padding(2);
            this.paymentbtn.Name = "paymentbtn";
            this.paymentbtn.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.paymentbtn.OnDisabledState.BorderRadius = 30;
            this.paymentbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.paymentbtn.OnDisabledState.BorderThickness = 1;
            this.paymentbtn.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.paymentbtn.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.paymentbtn.OnDisabledState.IconLeftImage = null;
            this.paymentbtn.OnDisabledState.IconRightImage = null;
            this.paymentbtn.onHoverState.BorderColor = System.Drawing.Color.Turquoise;
            this.paymentbtn.onHoverState.BorderRadius = 30;
            this.paymentbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.paymentbtn.onHoverState.BorderThickness = 1;
            this.paymentbtn.onHoverState.FillColor = System.Drawing.Color.Turquoise;
            this.paymentbtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.paymentbtn.onHoverState.IconLeftImage = null;
            this.paymentbtn.onHoverState.IconRightImage = null;
            this.paymentbtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.paymentbtn.OnIdleState.BorderRadius = 30;
            this.paymentbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.paymentbtn.OnIdleState.BorderThickness = 1;
            this.paymentbtn.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.paymentbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.paymentbtn.OnIdleState.IconLeftImage = global::Veterinary.Properties.Resources.icons8_money_96;
            this.paymentbtn.OnIdleState.IconRightImage = null;
            this.paymentbtn.OnPressedState.BorderColor = System.Drawing.Color.LightSeaGreen;
            this.paymentbtn.OnPressedState.BorderRadius = 30;
            this.paymentbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.paymentbtn.OnPressedState.BorderThickness = 1;
            this.paymentbtn.OnPressedState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.paymentbtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.paymentbtn.OnPressedState.IconLeftImage = null;
            this.paymentbtn.OnPressedState.IconRightImage = null;
            this.paymentbtn.Size = new System.Drawing.Size(178, 45);
            this.paymentbtn.TabIndex = 0;
            this.paymentbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.paymentbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.paymentbtn.TextMarginLeft = 0;
            this.paymentbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.paymentbtn.UseDefaultRadiusAndThickness = true;
            this.paymentbtn.Click += new System.EventHandler(this.paymentbtn_Click);
            // 
            // storebtn
            // 
            this.storebtn.AllowAnimations = true;
            this.storebtn.AllowMouseEffects = true;
            this.storebtn.AllowToggling = false;
            this.storebtn.AnimationSpeed = 200;
            this.storebtn.AutoGenerateColors = false;
            this.storebtn.AutoRoundBorders = false;
            this.storebtn.AutoSizeLeftIcon = true;
            this.storebtn.AutoSizeRightIcon = true;
            this.storebtn.BackColor = System.Drawing.Color.Transparent;
            this.storebtn.BackColor1 = System.Drawing.Color.Transparent;
            this.storebtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("storebtn.BackgroundImage")));
            this.storebtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.storebtn.ButtonText = "Store";
            this.storebtn.ButtonTextMarginLeft = 0;
            this.storebtn.ColorContrastOnClick = 45;
            this.storebtn.ColorContrastOnHover = 45;
            this.storebtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.storebtn.CustomizableEdges = borderEdges6;
            this.storebtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.storebtn.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.storebtn.DisabledFillColor = System.Drawing.Color.Transparent;
            this.storebtn.DisabledForecolor = System.Drawing.Color.White;
            this.storebtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.storebtn.Font = new System.Drawing.Font("Calibri", 10.875F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.storebtn.ForeColor = System.Drawing.Color.White;
            this.storebtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.storebtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.storebtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.storebtn.IconMarginLeft = 11;
            this.storebtn.IconPadding = 10;
            this.storebtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.storebtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.storebtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.storebtn.IconSize = 25;
            this.storebtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.storebtn.IdleBorderRadius = 30;
            this.storebtn.IdleBorderThickness = 1;
            this.storebtn.IdleFillColor = System.Drawing.Color.Transparent;
            this.storebtn.IdleIconLeftImage = global::Veterinary.Properties.Resources.icons8_petshop_68;
            this.storebtn.IdleIconRightImage = null;
            this.storebtn.IndicateFocus = false;
            this.storebtn.Location = new System.Drawing.Point(542, 77);
            this.storebtn.Margin = new System.Windows.Forms.Padding(2);
            this.storebtn.Name = "storebtn";
            this.storebtn.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.storebtn.OnDisabledState.BorderRadius = 30;
            this.storebtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.storebtn.OnDisabledState.BorderThickness = 1;
            this.storebtn.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.storebtn.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.storebtn.OnDisabledState.IconLeftImage = null;
            this.storebtn.OnDisabledState.IconRightImage = null;
            this.storebtn.onHoverState.BorderColor = System.Drawing.Color.Turquoise;
            this.storebtn.onHoverState.BorderRadius = 30;
            this.storebtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.storebtn.onHoverState.BorderThickness = 1;
            this.storebtn.onHoverState.FillColor = System.Drawing.Color.Turquoise;
            this.storebtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.storebtn.onHoverState.IconLeftImage = null;
            this.storebtn.onHoverState.IconRightImage = null;
            this.storebtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.storebtn.OnIdleState.BorderRadius = 30;
            this.storebtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.storebtn.OnIdleState.BorderThickness = 1;
            this.storebtn.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.storebtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.storebtn.OnIdleState.IconLeftImage = global::Veterinary.Properties.Resources.icons8_petshop_68;
            this.storebtn.OnIdleState.IconRightImage = null;
            this.storebtn.OnPressedState.BorderColor = System.Drawing.Color.LightSeaGreen;
            this.storebtn.OnPressedState.BorderRadius = 30;
            this.storebtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.storebtn.OnPressedState.BorderThickness = 1;
            this.storebtn.OnPressedState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.storebtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.storebtn.OnPressedState.IconLeftImage = null;
            this.storebtn.OnPressedState.IconRightImage = null;
            this.storebtn.Size = new System.Drawing.Size(145, 45);
            this.storebtn.TabIndex = 0;
            this.storebtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.storebtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.storebtn.TextMarginLeft = 0;
            this.storebtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.storebtn.UseDefaultRadiusAndThickness = true;
            this.storebtn.Click += new System.EventHandler(this.storebtn_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.pictureBox1.BackColor = System.Drawing.Color.Transparent;
            this.pictureBox1.BackgroundImage = global::Veterinary.Properties.Resources.female_doctor_and_male_doctor_standing_together;
            this.pictureBox1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pictureBox1.Location = new System.Drawing.Point(118, 308);
            this.pictureBox1.Margin = new System.Windows.Forms.Padding(2);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(310, 441);
            this.pictureBox1.TabIndex = 1;
            this.pictureBox1.TabStop = false;
            // 
            // pictureBox2
            // 
            this.pictureBox2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.pictureBox2.BackColor = System.Drawing.Color.Transparent;
            this.pictureBox2.BackgroundImage = global::Veterinary.Properties.Resources.white_dog_standing;
            this.pictureBox2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pictureBox2.Location = new System.Drawing.Point(0, 602);
            this.pictureBox2.Margin = new System.Windows.Forms.Padding(2);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(143, 147);
            this.pictureBox2.TabIndex = 2;
            this.pictureBox2.TabStop = false;
            // 
            // pictureBox3
            // 
            this.pictureBox3.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.pictureBox3.BackColor = System.Drawing.Color.Transparent;
            this.pictureBox3.BackgroundImage = global::Veterinary.Properties.Resources.cat_standing;
            this.pictureBox3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pictureBox3.Location = new System.Drawing.Point(409, 602);
            this.pictureBox3.Margin = new System.Windows.Forms.Padding(2);
            this.pictureBox3.Name = "pictureBox3";
            this.pictureBox3.Size = new System.Drawing.Size(182, 148);
            this.pictureBox3.TabIndex = 3;
            this.pictureBox3.TabStop = false;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Calibri", 19.875F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(11, 97);
            this.label1.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(118, 49);
            this.label1.TabIndex = 4;
            this.label1.Text = "Hello,";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.Transparent;
            this.label2.Font = new System.Drawing.Font("Calibri", 19.875F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(11, 159);
            this.label2.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(68, 49);
            this.label2.TabIndex = 4;
            this.label2.Text = "Dr.";
            // 
            // doctorname
            // 
            this.doctorname.AutoSize = true;
            this.doctorname.BackColor = System.Drawing.Color.Transparent;
            this.doctorname.Font = new System.Drawing.Font("Calibri", 19.875F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.doctorname.ForeColor = System.Drawing.Color.White;
            this.doctorname.Location = new System.Drawing.Point(83, 159);
            this.doctorname.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.doctorname.Name = "doctorname";
            this.doctorname.Size = new System.Drawing.Size(0, 49);
            this.doctorname.TabIndex = 4;
            // 
            // close
            // 
            this.close.BackColor = System.Drawing.Color.Transparent;
            this.close.BackgroundImage = global::Veterinary.Properties.Resources.icons8_close_90;
            this.close.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.close.Cursor = System.Windows.Forms.Cursors.Hand;
            this.close.Location = new System.Drawing.Point(1323, 1);
            this.close.Name = "close";
            this.close.Size = new System.Drawing.Size(30, 29);
            this.close.TabIndex = 6;
            this.close.TabStop = false;
            this.close.Click += new System.EventHandler(this.close_Click);
            // 
            // pensbtn
            // 
            this.pensbtn.AllowAnimations = true;
            this.pensbtn.AllowMouseEffects = true;
            this.pensbtn.AllowToggling = false;
            this.pensbtn.AnimationSpeed = 200;
            this.pensbtn.AutoGenerateColors = false;
            this.pensbtn.AutoRoundBorders = false;
            this.pensbtn.AutoSizeLeftIcon = true;
            this.pensbtn.AutoSizeRightIcon = true;
            this.pensbtn.BackColor = System.Drawing.Color.Transparent;
            this.pensbtn.BackColor1 = System.Drawing.Color.Transparent;
            this.pensbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pensbtn.BackgroundImage")));
            this.pensbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.pensbtn.ButtonText = "Pens";
            this.pensbtn.ButtonTextMarginLeft = 0;
            this.pensbtn.ColorContrastOnClick = 45;
            this.pensbtn.ColorContrastOnHover = 45;
            this.pensbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.pensbtn.CustomizableEdges = borderEdges7;
            this.pensbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.pensbtn.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.pensbtn.DisabledFillColor = System.Drawing.Color.Transparent;
            this.pensbtn.DisabledForecolor = System.Drawing.Color.White;
            this.pensbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.pensbtn.Font = new System.Drawing.Font("Calibri", 10.875F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.pensbtn.ForeColor = System.Drawing.Color.White;
            this.pensbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.pensbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.pensbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.pensbtn.IconMarginLeft = 11;
            this.pensbtn.IconPadding = 10;
            this.pensbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.pensbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.pensbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.pensbtn.IconSize = 25;
            this.pensbtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.pensbtn.IdleBorderRadius = 30;
            this.pensbtn.IdleBorderThickness = 1;
            this.pensbtn.IdleFillColor = System.Drawing.Color.Transparent;
            this.pensbtn.IdleIconLeftImage = global::Veterinary.Properties.Resources.icons8_pet_carrier_68;
            this.pensbtn.IdleIconRightImage = null;
            this.pensbtn.IndicateFocus = false;
            this.pensbtn.Location = new System.Drawing.Point(393, 77);
            this.pensbtn.Margin = new System.Windows.Forms.Padding(2);
            this.pensbtn.Name = "pensbtn";
            this.pensbtn.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.pensbtn.OnDisabledState.BorderRadius = 30;
            this.pensbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.pensbtn.OnDisabledState.BorderThickness = 1;
            this.pensbtn.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.pensbtn.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.pensbtn.OnDisabledState.IconLeftImage = null;
            this.pensbtn.OnDisabledState.IconRightImage = null;
            this.pensbtn.onHoverState.BorderColor = System.Drawing.Color.Turquoise;
            this.pensbtn.onHoverState.BorderRadius = 30;
            this.pensbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.pensbtn.onHoverState.BorderThickness = 1;
            this.pensbtn.onHoverState.FillColor = System.Drawing.Color.Turquoise;
            this.pensbtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.pensbtn.onHoverState.IconLeftImage = null;
            this.pensbtn.onHoverState.IconRightImage = null;
            this.pensbtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.pensbtn.OnIdleState.BorderRadius = 30;
            this.pensbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.pensbtn.OnIdleState.BorderThickness = 1;
            this.pensbtn.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.pensbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.pensbtn.OnIdleState.IconLeftImage = global::Veterinary.Properties.Resources.icons8_pet_carrier_68;
            this.pensbtn.OnIdleState.IconRightImage = null;
            this.pensbtn.OnPressedState.BorderColor = System.Drawing.Color.LightSeaGreen;
            this.pensbtn.OnPressedState.BorderRadius = 30;
            this.pensbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.pensbtn.OnPressedState.BorderThickness = 1;
            this.pensbtn.OnPressedState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.pensbtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.pensbtn.OnPressedState.IconLeftImage = null;
            this.pensbtn.OnPressedState.IconRightImage = null;
            this.pensbtn.Size = new System.Drawing.Size(145, 45);
            this.pensbtn.TabIndex = 0;
            this.pensbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.pensbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.pensbtn.TextMarginLeft = 0;
            this.pensbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.pensbtn.UseDefaultRadiusAndThickness = true;
            this.pensbtn.Click += new System.EventHandler(this.pensbtn_Click);
            // 
            // treatmentbtn
            // 
            this.treatmentbtn.AllowAnimations = true;
            this.treatmentbtn.AllowMouseEffects = true;
            this.treatmentbtn.AllowToggling = false;
            this.treatmentbtn.AnimationSpeed = 200;
            this.treatmentbtn.AutoGenerateColors = false;
            this.treatmentbtn.AutoRoundBorders = false;
            this.treatmentbtn.AutoSizeLeftIcon = true;
            this.treatmentbtn.AutoSizeRightIcon = true;
            this.treatmentbtn.BackColor = System.Drawing.Color.Transparent;
            this.treatmentbtn.BackColor1 = System.Drawing.Color.Transparent;
            this.treatmentbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("treatmentbtn.BackgroundImage")));
            this.treatmentbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.treatmentbtn.ButtonText = "Treatment";
            this.treatmentbtn.ButtonTextMarginLeft = 0;
            this.treatmentbtn.ColorContrastOnClick = 45;
            this.treatmentbtn.ColorContrastOnHover = 45;
            this.treatmentbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.treatmentbtn.CustomizableEdges = borderEdges8;
            this.treatmentbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.treatmentbtn.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.treatmentbtn.DisabledFillColor = System.Drawing.Color.Transparent;
            this.treatmentbtn.DisabledForecolor = System.Drawing.Color.White;
            this.treatmentbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.treatmentbtn.Font = new System.Drawing.Font("Calibri", 10.875F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.treatmentbtn.ForeColor = System.Drawing.Color.White;
            this.treatmentbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.treatmentbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.treatmentbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.treatmentbtn.IconMarginLeft = 11;
            this.treatmentbtn.IconPadding = 10;
            this.treatmentbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.treatmentbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.treatmentbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.treatmentbtn.IconSize = 20;
            this.treatmentbtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.treatmentbtn.IdleBorderRadius = 30;
            this.treatmentbtn.IdleBorderThickness = 1;
            this.treatmentbtn.IdleFillColor = System.Drawing.Color.Transparent;
            this.treatmentbtn.IdleIconLeftImage = global::Veterinary.Properties.Resources.icons8_treatment_60;
            this.treatmentbtn.IdleIconRightImage = null;
            this.treatmentbtn.IndicateFocus = false;
            this.treatmentbtn.Location = new System.Drawing.Point(1092, 19);
            this.treatmentbtn.Margin = new System.Windows.Forms.Padding(2);
            this.treatmentbtn.Name = "treatmentbtn";
            this.treatmentbtn.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.treatmentbtn.OnDisabledState.BorderRadius = 30;
            this.treatmentbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.treatmentbtn.OnDisabledState.BorderThickness = 1;
            this.treatmentbtn.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.treatmentbtn.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.treatmentbtn.OnDisabledState.IconLeftImage = null;
            this.treatmentbtn.OnDisabledState.IconRightImage = null;
            this.treatmentbtn.onHoverState.BorderColor = System.Drawing.Color.Turquoise;
            this.treatmentbtn.onHoverState.BorderRadius = 30;
            this.treatmentbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.treatmentbtn.onHoverState.BorderThickness = 1;
            this.treatmentbtn.onHoverState.FillColor = System.Drawing.Color.Turquoise;
            this.treatmentbtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.treatmentbtn.onHoverState.IconLeftImage = null;
            this.treatmentbtn.onHoverState.IconRightImage = null;
            this.treatmentbtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.treatmentbtn.OnIdleState.BorderRadius = 30;
            this.treatmentbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.treatmentbtn.OnIdleState.BorderThickness = 1;
            this.treatmentbtn.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.treatmentbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.treatmentbtn.OnIdleState.IconLeftImage = global::Veterinary.Properties.Resources.icons8_treatment_60;
            this.treatmentbtn.OnIdleState.IconRightImage = null;
            this.treatmentbtn.OnPressedState.BorderColor = System.Drawing.Color.LightSeaGreen;
            this.treatmentbtn.OnPressedState.BorderRadius = 30;
            this.treatmentbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.treatmentbtn.OnPressedState.BorderThickness = 1;
            this.treatmentbtn.OnPressedState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.treatmentbtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.treatmentbtn.OnPressedState.IconLeftImage = null;
            this.treatmentbtn.OnPressedState.IconRightImage = null;
            this.treatmentbtn.Size = new System.Drawing.Size(200, 45);
            this.treatmentbtn.TabIndex = 0;
            this.treatmentbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.treatmentbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.treatmentbtn.TextMarginLeft = 0;
            this.treatmentbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.treatmentbtn.UseDefaultRadiusAndThickness = true;
            this.treatmentbtn.Click += new System.EventHandler(this.treatmentbtn_Click);
            // 
            // flowLayoutPanel1
            // 
            this.flowLayoutPanel1.BackColor = System.Drawing.Color.Transparent;
            this.flowLayoutPanel1.Location = new System.Drawing.Point(632, 295);
            this.flowLayoutPanel1.Name = "flowLayoutPanel1";
            this.flowLayoutPanel1.Size = new System.Drawing.Size(712, 443);
            this.flowLayoutPanel1.TabIndex = 7;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Font = new System.Drawing.Font("Gabriola", 20F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(839, 203);
            this.label3.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(324, 74);
            this.label3.TabIndex = 4;
            this.label3.Text = "Today\'s Appointments";
            // 
            // pictureBox4
            // 
            this.pictureBox4.BackColor = System.Drawing.Color.Transparent;
            this.pictureBox4.BackgroundImage = global::Veterinary.Properties.Resources.icons8_appointment_60;
            this.pictureBox4.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pictureBox4.Location = new System.Drawing.Point(752, 203);
            this.pictureBox4.Name = "pictureBox4";
            this.pictureBox4.Size = new System.Drawing.Size(66, 74);
            this.pictureBox4.TabIndex = 8;
            this.pictureBox4.TabStop = false;
            // 
            // ordersbtn
            // 
            this.ordersbtn.AllowAnimations = true;
            this.ordersbtn.AllowMouseEffects = true;
            this.ordersbtn.AllowToggling = false;
            this.ordersbtn.AnimationSpeed = 200;
            this.ordersbtn.AutoGenerateColors = false;
            this.ordersbtn.AutoRoundBorders = false;
            this.ordersbtn.AutoSizeLeftIcon = true;
            this.ordersbtn.AutoSizeRightIcon = true;
            this.ordersbtn.BackColor = System.Drawing.Color.Transparent;
            this.ordersbtn.BackColor1 = System.Drawing.Color.Transparent;
            this.ordersbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ordersbtn.BackgroundImage")));
            this.ordersbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ordersbtn.ButtonText = "Orders";
            this.ordersbtn.ButtonTextMarginLeft = 0;
            this.ordersbtn.ColorContrastOnClick = 45;
            this.ordersbtn.ColorContrastOnHover = 45;
            this.ordersbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.ordersbtn.CustomizableEdges = borderEdges9;
            this.ordersbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ordersbtn.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.ordersbtn.DisabledFillColor = System.Drawing.Color.Transparent;
            this.ordersbtn.DisabledForecolor = System.Drawing.Color.White;
            this.ordersbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ordersbtn.Font = new System.Drawing.Font("Calibri", 10.875F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ordersbtn.ForeColor = System.Drawing.Color.White;
            this.ordersbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ordersbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ordersbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ordersbtn.IconMarginLeft = 11;
            this.ordersbtn.IconPadding = 10;
            this.ordersbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ordersbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ordersbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ordersbtn.IconSize = 25;
            this.ordersbtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.ordersbtn.IdleBorderRadius = 30;
            this.ordersbtn.IdleBorderThickness = 1;
            this.ordersbtn.IdleFillColor = System.Drawing.Color.Transparent;
            this.ordersbtn.IdleIconLeftImage = global::Veterinary.Properties.Resources.icons8_order_64;
            this.ordersbtn.IdleIconRightImage = null;
            this.ordersbtn.IndicateFocus = false;
            this.ordersbtn.Location = new System.Drawing.Point(869, 77);
            this.ordersbtn.Margin = new System.Windows.Forms.Padding(2);
            this.ordersbtn.Name = "ordersbtn";
            this.ordersbtn.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.ordersbtn.OnDisabledState.BorderRadius = 30;
            this.ordersbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ordersbtn.OnDisabledState.BorderThickness = 1;
            this.ordersbtn.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.ordersbtn.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.ordersbtn.OnDisabledState.IconLeftImage = null;
            this.ordersbtn.OnDisabledState.IconRightImage = null;
            this.ordersbtn.onHoverState.BorderColor = System.Drawing.Color.Turquoise;
            this.ordersbtn.onHoverState.BorderRadius = 30;
            this.ordersbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ordersbtn.onHoverState.BorderThickness = 1;
            this.ordersbtn.onHoverState.FillColor = System.Drawing.Color.Turquoise;
            this.ordersbtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ordersbtn.onHoverState.IconLeftImage = null;
            this.ordersbtn.onHoverState.IconRightImage = null;
            this.ordersbtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.ordersbtn.OnIdleState.BorderRadius = 30;
            this.ordersbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ordersbtn.OnIdleState.BorderThickness = 1;
            this.ordersbtn.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.ordersbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.ordersbtn.OnIdleState.IconLeftImage = global::Veterinary.Properties.Resources.icons8_order_64;
            this.ordersbtn.OnIdleState.IconRightImage = null;
            this.ordersbtn.OnPressedState.BorderColor = System.Drawing.Color.LightSeaGreen;
            this.ordersbtn.OnPressedState.BorderRadius = 30;
            this.ordersbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ordersbtn.OnPressedState.BorderThickness = 1;
            this.ordersbtn.OnPressedState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.ordersbtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ordersbtn.OnPressedState.IconLeftImage = null;
            this.ordersbtn.OnPressedState.IconRightImage = null;
            this.ordersbtn.Size = new System.Drawing.Size(163, 45);
            this.ordersbtn.TabIndex = 0;
            this.ordersbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ordersbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ordersbtn.TextMarginLeft = 0;
            this.ordersbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.ordersbtn.UseDefaultRadiusAndThickness = true;
            this.ordersbtn.Click += new System.EventHandler(this.ordersbtn_Click);
            // 
            // medbtn
            // 
            this.medbtn.AllowAnimations = true;
            this.medbtn.AllowMouseEffects = true;
            this.medbtn.AllowToggling = false;
            this.medbtn.AnimationSpeed = 200;
            this.medbtn.AutoGenerateColors = false;
            this.medbtn.AutoRoundBorders = false;
            this.medbtn.AutoSizeLeftIcon = true;
            this.medbtn.AutoSizeRightIcon = true;
            this.medbtn.BackColor = System.Drawing.Color.Transparent;
            this.medbtn.BackColor1 = System.Drawing.Color.Transparent;
            this.medbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("medbtn.BackgroundImage")));
            this.medbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.medbtn.ButtonText = "Medications";
            this.medbtn.ButtonTextMarginLeft = 0;
            this.medbtn.ColorContrastOnClick = 45;
            this.medbtn.ColorContrastOnHover = 45;
            this.medbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.medbtn.CustomizableEdges = borderEdges10;
            this.medbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.medbtn.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.medbtn.DisabledFillColor = System.Drawing.Color.Transparent;
            this.medbtn.DisabledForecolor = System.Drawing.Color.White;
            this.medbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.medbtn.Font = new System.Drawing.Font("Calibri", 10.875F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.medbtn.ForeColor = System.Drawing.Color.White;
            this.medbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.medbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.medbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.medbtn.IconMarginLeft = 11;
            this.medbtn.IconPadding = 10;
            this.medbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.medbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.medbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.medbtn.IconSize = 25;
            this.medbtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.medbtn.IdleBorderRadius = 30;
            this.medbtn.IdleBorderThickness = 1;
            this.medbtn.IdleFillColor = System.Drawing.Color.Transparent;
            this.medbtn.IdleIconLeftImage = global::Veterinary.Properties.Resources.icons8_medication_64;
            this.medbtn.IdleIconRightImage = null;
            this.medbtn.IndicateFocus = false;
            this.medbtn.Location = new System.Drawing.Point(1036, 77);
            this.medbtn.Margin = new System.Windows.Forms.Padding(2);
            this.medbtn.Name = "medbtn";
            this.medbtn.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.medbtn.OnDisabledState.BorderRadius = 30;
            this.medbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.medbtn.OnDisabledState.BorderThickness = 1;
            this.medbtn.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.medbtn.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.medbtn.OnDisabledState.IconLeftImage = null;
            this.medbtn.OnDisabledState.IconRightImage = null;
            this.medbtn.onHoverState.BorderColor = System.Drawing.Color.Turquoise;
            this.medbtn.onHoverState.BorderRadius = 30;
            this.medbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.medbtn.onHoverState.BorderThickness = 1;
            this.medbtn.onHoverState.FillColor = System.Drawing.Color.Turquoise;
            this.medbtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.medbtn.onHoverState.IconLeftImage = null;
            this.medbtn.onHoverState.IconRightImage = null;
            this.medbtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.medbtn.OnIdleState.BorderRadius = 30;
            this.medbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.medbtn.OnIdleState.BorderThickness = 1;
            this.medbtn.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.medbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.medbtn.OnIdleState.IconLeftImage = global::Veterinary.Properties.Resources.icons8_medication_64;
            this.medbtn.OnIdleState.IconRightImage = null;
            this.medbtn.OnPressedState.BorderColor = System.Drawing.Color.LightSeaGreen;
            this.medbtn.OnPressedState.BorderRadius = 30;
            this.medbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.medbtn.OnPressedState.BorderThickness = 1;
            this.medbtn.OnPressedState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.medbtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.medbtn.OnPressedState.IconLeftImage = null;
            this.medbtn.OnPressedState.IconRightImage = null;
            this.medbtn.Size = new System.Drawing.Size(198, 45);
            this.medbtn.TabIndex = 0;
            this.medbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.medbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.medbtn.TextMarginLeft = 0;
            this.medbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.medbtn.UseDefaultRadiusAndThickness = true;
            this.medbtn.Click += new System.EventHandler(this.medbtn_Click);
            // 
            // Form1
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.AutoSize = true;
            this.BackgroundImage = global::Veterinary.Properties.Resources.background_2;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(1356, 750);
            this.Controls.Add(this.pictureBox4);
            this.Controls.Add(this.flowLayoutPanel1);
            this.Controls.Add(this.close);
            this.Controls.Add(this.doctorname);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.pictureBox3);
            this.Controls.Add(this.pictureBox2);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.treatmentbtn);
            this.Controls.Add(this.pensbtn);
            this.Controls.Add(this.storebtn);
            this.Controls.Add(this.medbtn);
            this.Controls.Add(this.ordersbtn);
            this.Controls.Add(this.paymentbtn);
            this.Controls.Add(this.consultationbtn);
            this.Controls.Add(this.appointmentbtn);
            this.Controls.Add(this.ownerbtn);
            this.Controls.Add(this.animalbtn);
            this.DoubleBuffered = true;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "Form1";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.Form1_Load);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.close)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox4)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton animalbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ownerbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton appointmentbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton consultationbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton paymentbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton storebtn;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.PictureBox pictureBox2;
        private System.Windows.Forms.PictureBox pictureBox3;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label doctorname;
        private System.Windows.Forms.PictureBox close;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton pensbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton treatmentbtn;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel1;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.PictureBox pictureBox4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ordersbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton medbtn;
    }
}

